DEFINE
	VAR BillToNumber = {
		"87947"
	}

	VAR AcctNumber = {
		"87947"
	}

	VAR __DS0FilterTable1 =
	TREATAS(
		AcctNumber,
		'JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Acct #]
	)

	VAR __DS0FilterTable =
	TREATAS(
		BillToNumber,
		'JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Bill To #]
	)

	VAR __DS0FilterTable2 =
	FILTER(
		KEEPFILTERS(VALUES('JDE 90-Price Code Expiration Dates-F4072WMT'[Price Code])),
		NOT (ISBLANK('JDE 90-Price Code Expiration Dates-F4072WMT'[Price Code]))
	)

	VAR __DS0FilterTable3 =
	TREATAS(
		{
			"Yes"
		},
		'JDE 90-Price Code Expiration Dates-F4072WMT'[Expiration Date within 180 Days?]
	)

	VAR __DS0Core =
	SELECTCOLUMNS(
		KEEPFILTERS(FILTER(
			KEEPFILTERS(SUMMARIZECOLUMNS(
				'JDE 90-Price Code Expiration Dates-F4072WMT'[Price Code],
				'JDE 90-Price Code Expiration Dates-F4072WMT'[Effective Date],
				'JDE 90-Price Code Expiration Dates-F4072WMT'[Expiration Date],
				'JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Adjustment Description],
				'JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Acct #],
				'JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Acct Name],
				__DS0FilterTable1,
				__DS0FilterTable,
				__DS0FilterTable2,
				__DS0FilterTable3,
				"CountRowsJDE_90_Price_Code_Expiration_Dates_F4072WMT", COUNTROWS('JDE 90-Price Code Expiration Dates-F4072WMT')
			)
			),
			OR(
				OR(
					OR(
						OR(
							OR(
								NOT (ISBLANK('JDE 90-Price Code Expiration Dates-F4072WMT'[Price Code])),
								NOT (ISBLANK('JDE 90-Price Code Expiration Dates-F4072WMT'[Effective Date]))
							),
							NOT (ISBLANK('JDE 90-Price Code Expiration Dates-F4072WMT'[Expiration Date]))
						),
						NOT (ISBLANK('JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Adjustment Description]))
					),
					NOT (ISBLANK('JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Acct #]))
				),
				NOT (ISBLANK('JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Acct Name]))
			)
		)
		),
		"PriceCodeDescription", 'JDE 90-Price Code Expiration Dates-F4072WMT'[Price Code] & " - " & 'JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Adjustment Description],
		//"Description", 'JDE 90-Anchor-Price Code, BT, ST-F4072WMT'[Adjustment Description],
		"EffectiveDate", FORMAT(
			'JDE 90-Price Code Expiration Dates-F4072WMT'[Effective Date],
			"mm/dd/yyyy"
		),
		"ExpirationDate", FORMAT(
			'JDE 90-Price Code Expiration Dates-F4072WMT'[Expiration Date],
			"mm/dd/yyyy"
		)
	)

EVALUATE
	__DS0Core
	ORDER BY "PriceCodeDescription"